---
title: "HW 01 - Pet names"
author: "hugo baba"
date: "february 3, 2026"
output: github_document
---

## Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse)
library(openintro)
```

## Exercises

### Exercise 1
```{r}
View(seattlepets)
nrow(seattlepets)
```

There are `r nrow(seattlepets)` pets in the dataset.

### Exercise 2

There are `r ncol(seattlepets)` columns in the dataset.

### Exercise 3


```{r most-common-names}
seattlepets %>%
  count(animal_name, sort = TRUE)
```
The top three names are Lucy, Charlie and Luna.

### Exercise 4


```{r most-common-cat-dog-names}
seattlepets |> 
  group_by(species) |> 
  count(animal_name, sort = TRUE)
```

```{r}
seattlepets |>
  count(species, sort = TRUE)
```

```{r}
seattlepets |>
  group_by(species) |> 
  count(animal_name, sort = TRUE) |>
    slice_max(n, n = 20) 
  
```

### Exercise 5

```{r cat-dog-name-plot}
cats_n_dogs <- seattlepets |>
  group_by(species) |> 
  filter(species %in% c("Cat", "Dog")) |>
  count(animal_name, sort = TRUE) |>
  slice_max(n, n = 20)
```

```{r plot-cats-dogs}
name_props <- cats_n_dogs |>
  group_by(species) |> 
  mutate(props = n / sum(n))

 dogs_props <- name_props |>
  filter(species == "Dog") |> 
  rename(dog_prop = props)

 cats_props <- name_props |>
  filter(species == "Cat") |> 
  rename(cat_prop = props)
```

### Exercise 6

Remove this text, and add your answer for Exercise 6 here.
